name: Executar Automação de Ponto
on:
  schedule:
    # Agendado usando o fuso horário UTC.                                                          
    # 10:00 da manhã no Brasil (Horário de Brasília, UTC-3) equivale a 13:00 UTC.
    # Rodar de segunda a sexta às 10:00 BRT
    - cron: '0 13 * * 1-5'
  workflow_dispatch: # Permite que o workflow seja executado manualmente a partir da interface do GitHub Actions.

jobs:
  run-automation:
    runs-on: ubuntu-latest
    environment: Ponto
    steps:
      # 1. Baixar o codigo do repositorio
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Configurar o ambiente Go (com cache de módulos)
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21' # Versão do Go que você deseja usar
          cache-dependency-path: ./Ponto/go.sum

      # 3. Roda o script passando as credenciais seguras do github secrets
      - name: Run Script
        working-directory: ./Ponto
        env:
          URL: ${{ secrets.URL }}
          MATRICULA: ${{ secrets.MATRICULA }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          go run main.go

      # 4. Salvar o screenshot gerado como um artefato do GitHub Actions
      - name: Upload Screenshot
        uses: actions/upload-artifact@v4
        with:
          name: screenshot-execucao
          path: ./Ponto/screenshot.png
          if-no-files-found: warn # Avisa no log se o arquivo do screenshot não foi encontrado